version: '3'
services:
    jenkins:
        build: ./jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ../ecs_deploy:/pipeline-dev
            - ./disable_script_security.groovy:/var/jenkins_home/init.groovy.d/disable-script-security.groovy
        environment:
            JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
            - "18080:8080"
    # nexus:
    #     image: sonatype/nexus
    #     ports:
    #         - "18081:8081"
